#!/bin/sh
# Codex wiring for this repository.
#
# Codex finds the skills on its own (it reads `~/.agents/skills`, which the
# README links), so this script covers the four things it cannot work out:
#
#   1. the router + this harness's runtime file, injected every turn by a
#      UserPromptSubmit hook in $CODEX_HOME/hooks.json
#   2. the standing instructions, as $CODEX_HOME/AGENTS.md -> instructions/AGENTS.md
#   3. the short commands, as $CODEX_HOME/prompts/<name>.md -> commands/<name>.md
#   4. the subagents, generated into $CODEX_HOME/agents/<name>.toml, because
#      Codex defines a custom agent in TOML and cannot read the markdown ones
#
# It owns exactly those, the same ground the Claude Code plugin covers with its
# hook: other hook events, other hooks on UserPromptSubmit, and every other key
# in the config are yours and are left alone.
#
#   usage: harness/codex/install.sh [--dry-run]
#
# Nothing here is specific to a machine or a project: the repository root comes
# from this script's own location and the namespace from the marketplace
# manifest, so a stranger's clone wires itself up the same way.
set -eu

DRY_RUN=0
[ "${1:-}" = "--dry-run" ] && DRY_RUN=1

command -v jq >/dev/null 2>&1 || { echo "jq is required" >&2; exit 1; }

# Resolve through the symlink, not along it: this file may be reached from an
# install location that is itself a link back into the clone.
REPO="$(cd "$(dirname "$0")/../.." && pwd -P)"
NS="$(jq -r .name "$REPO/.claude-plugin/marketplace.json")"
[ -n "$NS" ] && [ "$NS" != "null" ] || { echo "no namespace in .claude-plugin/marketplace.json" >&2; exit 1; }

CODEX_HOME="${CODEX_HOME:-$HOME/.codex}"
RUNTIME="$REPO/harness/codex/codex.md"
HOOK="$REPO/harness/codex/router-inject.sh"
HOOKS="$CODEX_HOME/hooks.json"

[ -f "$RUNTIME" ] || { echo "missing $RUNTIME" >&2; exit 1; }
[ -f "$HOOK" ] || { echo "missing $HOOK" >&2; exit 1; }
[ -f "$REPO/skills/router/SKILL.md" ] || echo "note: $REPO/skills/router/SKILL.md does not exist — the hook will inject a placeholder" >&2

if [ -f "$HOOKS" ]; then
  jq empty "$HOOKS" >/dev/null 2>&1 || {
    echo "$HOOKS is not parseable as JSON — merge by hand" >&2
    exit 1
  }
fi

# Drop any handler of ours (or from an earlier location of this script) from the
# UserPromptSubmit list, then drop the groups that leaves empty, then append the
# current one. Every other event, and anyone else's UserPromptSubmit hook, is
# carried through untouched. additionalContextLimit 0 means "no spill file": the
# router is far longer than the ~2500-token default and must arrive whole.
MERGED="$({ [ -f "$HOOKS" ] && cat "$HOOKS" || echo '{}'; } | jq \
  --arg cmd "$HOOK" \
  --arg prefix "$REPO/harness/" \
  --arg status "Loading the $NS router" \
  '(.hooks //= {})
   | .hooks.UserPromptSubmit = (
       ((.hooks.UserPromptSubmit // [])
         | map(.hooks = ((.hooks // []) | map(select((.command // "") | startswith($prefix) | not))))
         | map(select((.hooks | length) > 0)))
       + [{hooks: [{type: "command",
                    command: $cmd,
                    statusMessage: $status,
                    additionalContextLimit: 0,
                    timeout: 30}]}])')"

# The generator for the subagents: Codex wants one TOML file per agent, with
# name, description and developer_instructions. Markdown frontmatter keys that
# mean nothing here (mode, model) are deliberately not carried over — a Claude
# model slug is not a Codex one.
gen_agents() {
  python3 - "$REPO/agents" "$CODEX_HOME/agents" "$REPO" <<'PY'
import json, os, sys

src, dest, repo = sys.argv[1], sys.argv[2], sys.argv[3]
STAMP = "# generated by harness/codex/install.sh"
MARK = "%s from %s/agents — edits are overwritten" % (STAMP, repo)
os.makedirs(dest, exist_ok=True)

def frontmatter(text):
    """The subset of YAML these agent files actually use."""
    if not text.startswith("---"):
        return {}, text
    end = text.find("\n---", 3)
    if end == -1:
        return {}, text
    head, body = text[3:end], text[end + 4:]
    data, key, buf = {}, None, []
    for line in head.splitlines():
        if buf is not None and key and (line.startswith("  ") or not line.strip()):
            buf.append(line.strip())
            continue
        if key and buf:
            data[key] = " ".join(b for b in buf if b)
        key, buf = None, None
        if ":" not in line:
            continue
        k, v = line.split(":", 1)
        k, v = k.strip(), v.strip()
        if v in (">", ">-", "|", "|-"):
            key, buf = k, []
        elif v[:1] == '"':
            try:
                data[k] = json.loads(v)
            except ValueError:
                data[k] = v.strip('"')
        else:
            data[k] = v.strip("'")
    if key and buf:
        data[key] = " ".join(b for b in buf if b)
    return data, body.lstrip("\n")

written = []
for root, _, files in os.walk(src):
    for f in sorted(files):
        if not f.endswith(".md"):
            continue
        meta, body = frontmatter(open(os.path.join(root, f), encoding="utf-8").read())
        name = meta.get("name") or os.path.splitext(f)[0]
        out = os.path.join(dest, name + ".toml")
        with open(out, "w", encoding="utf-8") as fh:
            fh.write(MARK + "\n")
            fh.write("name = %s\n" % json.dumps(name))
            fh.write("description = %s\n" % json.dumps(meta.get("description", name)))
            fh.write("developer_instructions = %s\n" % json.dumps(body))
        written.append(out)

# Ours and ours only: a file we generated for an agent that no longer exists.
for f in sorted(os.listdir(dest)):
    p = os.path.join(dest, f)
    if p in written or not f.endswith(".toml"):
        continue
    with open(p, encoding="utf-8") as fh:
        if fh.readline().startswith(STAMP):
            os.remove(p)

print("\n".join(written))
PY
}

if [ "$DRY_RUN" -eq 1 ]; then
  printf '%s\n' "$MERGED"
  echo "--- would also link ---" >&2
  echo "  $CODEX_HOME/AGENTS.md -> $REPO/instructions/AGENTS.md" >&2
  for f in "$REPO"/commands/*.md; do
    [ -f "$f" ] && echo "  $CODEX_HOME/prompts/$(basename "$f") -> $f" >&2
  done
  echo "--- would generate ---" >&2
  for f in "$REPO"/agents/*/*.md "$REPO"/agents/*.md; do
    [ -f "$f" ] && echo "  $CODEX_HOME/agents/$(basename "$f" .md).toml" >&2
  done
  exit 0
fi

mkdir -p "$CODEX_HOME" "$CODEX_HOME/prompts" "$CODEX_HOME/agents"

[ -f "$HOOKS" ] && cp -p "$HOOKS" "$HOOKS.bak"
printf '%s\n' "$MERGED" > "$HOOKS.tmp"
mv "$HOOKS.tmp" "$HOOKS"

# Standing instructions. A real file there is the user's own writing, so it is
# moved aside rather than destroyed.
if [ -f "$REPO/instructions/AGENTS.md" ]; then
  if [ -f "$CODEX_HOME/AGENTS.md" ] && [ ! -L "$CODEX_HOME/AGENTS.md" ]; then
    mv "$CODEX_HOME/AGENTS.md" "$CODEX_HOME/AGENTS.md.bak"
    echo "kept your previous $CODEX_HOME/AGENTS.md as AGENTS.md.bak"
  fi
  rm -f "$CODEX_HOME/AGENTS.md"
  ln -s "$REPO/instructions/AGENTS.md" "$CODEX_HOME/AGENTS.md"
fi

# Short commands. Codex offers them as /prompts:<name>.
for f in "$REPO"/commands/*.md; do
  [ -f "$f" ] || continue
  ln -sf "$f" "$CODEX_HOME/prompts/$(basename "$f")"
done

if [ -d "$REPO/agents" ]; then
  if command -v python3 >/dev/null 2>&1; then
    gen_agents > /dev/null
  else
    echo "note: python3 not found — $CODEX_HOME/agents was left alone, so the subagents are missing here" >&2
  fi
fi

echo "wired $NS into $CODEX_HOME"
jq -r --arg h "$HOOKS" '"  \($h):", (.hooks | to_entries[] | "    \(.key): \([.value[].hooks[].command // "mcp_tool"] | join(", "))")' "$HOOKS"
echo "  $CODEX_HOME/AGENTS.md -> $(readlink "$CODEX_HOME/AGENTS.md" 2>/dev/null || echo 'not linked')"
echo "  prompts: $(ls "$CODEX_HOME/prompts" 2>/dev/null | tr '\n' ' ')"
echo "  agents:  $(ls "$CODEX_HOME/agents" 2>/dev/null | tr '\n' ' ')"
echo
echo "Codex skips a new or changed hook until you trust it: run /hooks in Codex and trust the $NS entry."
